language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

script: 
  - DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
  - mvn clean package -f at.bestsolution.fx.test/pom.xml
