language: java
sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.m2

script: 
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
  - export MAVEN_OPTS="-Djava.awt.headless=true -Dprism.order=sw -Dprism.text=t2k"
  - mvn clean package -f at.bestsolution.fx.test/pom.xml
  - cd e4-test/sample.osgi.app.app.releng
  - mvn clean integration-test